const data = [
  {
    key: "1",
    value: "Food",
    icon: "FoodIcon",
    color: "blue",
    fill: "lightblue",
  },
  {
    key: "2",
    value: "Groceries",
    icon: "ShoppingCartIcon",
    color: "green",
    fill: "lightgreen",
  },
  {
    key: "3",
    value: "Rent",
    icon: "HomeIcon",
    color: "brown",
    fill: "burlywood",
  },
  { key: "4", value: "Fuel", icon: "FuelIcon", color: "black", fill: "gray" },
  {
    key: "5",
    value: "Film",
    icon: "FilmIcon",
    color: "red",
    fill: "lightcoral",
  },
  {
    key: "6",
    value: "Utilities",
    icon: "UtilitiesIcon",
    color: "orange",
    fill: "goldenrod",
  },
  {
    key: "7",
    value: "Shopping",
    icon: "ShoppingBagIcon",
    color: "purple",
    fill: "plum",
  },
  {
    key: "8",
    value: "Transportation",
    icon: "CarIcon",
    color: "blue",
    fill: "lightblue",
  },
  {
    key: "9",
    value: "Entertainment",
    icon: "EntertainmentIcon",
    color: "magenta",
    fill: "pink",
  },
  {
    key: "10",
    value: "Dining Out",
    icon: "FoodIcon",
    color: "red",
    fill: "salmon",
  },
  {
    key: "11",
    value: "Healthcare",
    icon: "HealthcareIcon",
    color: "teal",
    fill: "lightseagreen",
  },
  {
    key: "12",
    value: "Education",
    icon: "EducationIcon",
    color: "blue",
    fill: "skyblue",
  },
  {
    key: "13",
    value: "Subscriptions",
    icon: "SubscriptionIcon",
    color: "gold",
    fill: "khaki",
  },
  {
    key: "14",
    value: "Travel",
    icon: "TravelIcon",
    color: "cyan",
    fill: "turquoise",
  },
  {
    key: "15",
    value: "Others",
    icon: "OthersIcon",
    color: "gray",
    fill: "lightgray",
  },
]

export default data